ALTER TABLE public.financial_settings
  ADD COLUMN IF NOT EXISTS payment_processor TEXT NOT NULL DEFAULT 'Custom',
  ADD COLUMN IF NOT EXISTS fee_in_person_pct NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fee_in_person_flat NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fee_online_pct NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fee_online_flat NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fee_keyed_pct NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fee_keyed_flat NUMERIC NOT NULL DEFAULT 0;

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS cc_transaction_type TEXT;